apiVersion: v1
kind: Service
metadata:
  name: status-service
spec:
  selector:
    app: status-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer  # Balanceador de carga para distribuir requisições
